name: Xcode Build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Swift
      uses: swift-actions/setup-swift@v1.23.0
      with:
        swift-version: 5.8
